// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
)

type (
	IRbac interface {
		Rbac_test(ctx context.Context, sub string, obj string, act string) (err int)
	}
)

var (
	localRbac IRbac
)

func Rbac() IRbac {
	if localRbac == nil {
		panic("implement not found for interface IRbac, forgot register?")
	}
	return localRbac
}

func RegisterRbac(i IRbac) {
	localRbac = i
}
