// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf2/internal/dao/internal"
)

// internalAdmin1Dao is internal type for wrapping internal DAO implements.
type internalAdmin1Dao = *internal.Admin1Dao

// admin1Dao is the data access object for table admin1无用.
// You can define custom methods on it to extend its functionality as you wish.
type admin1Dao struct {
	internalAdmin1Dao
}

var (
	// Admin1 is globally public accessible object for table admin1无用 operations.
	Admin1 = admin1Dao{
		internal.NewAdmin1Dao(),
	}
)

// Fill with you ideas below.
