// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf2/internal/dao/internal"
)

// internalJobGangweiDao is internal type for wrapping internal DAO implements.
type internalJobGangweiDao = *internal.JobGangweiDao

// jobGangweiDao is the data access object for table job_gangwei.
// You can define custom methods on it to extend its functionality as you wish.
type jobGangweiDao struct {
	internalJobGangweiDao
}

var (
	// JobGangwei is globally public accessible object for table job_gangwei operations.
	JobGangwei = jobGangweiDao{
		internal.NewJobGangweiDao(),
	}
)

// Fill with you ideas below.
