// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf2/internal/dao/internal"
)

// internalRenCaiZhaoPinDao is internal type for wrapping internal DAO implements.
type internalRenCaiZhaoPinDao = *internal.RenCaiZhaoPinDao

// renCaiZhaoPinDao is the data access object for table ren_cai_zhao_pin.
// You can define custom methods on it to extend its functionality as you wish.
type renCaiZhaoPinDao struct {
	internalRenCaiZhaoPinDao
}

var (
	// RenCaiZhaoPin is globally public accessible object for table ren_cai_zhao_pin operations.
	RenCaiZhaoPin = renCaiZhaoPinDao{
		internal.NewRenCaiZhaoPinDao(),
	}
)

// Fill with you ideas below.
