// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf2/internal/dao/internal"
)

// internalTestRedisDao is internal type for wrapping internal DAO implements.
type internalTestRedisDao = *internal.TestRedisDao

// testRedisDao is the data access object for table test_redis.
// You can define custom methods on it to extend its functionality as you wish.
type testRedisDao struct {
	internalTestRedisDao
}

var (
	// TestRedis is globally public accessible object for table test_redis operations.
	TestRedis = testRedisDao{
		internal.NewTestRedisDao(),
	}
)

// Fill with you ideas below.
