// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf2/internal/dao/internal"
)

// internalUserApiLimitDao is internal type for wrapping internal DAO implements.
type internalUserApiLimitDao = *internal.UserApiLimitDao

// userApiLimitDao is the data access object for table user_api_limit.
// You can define custom methods on it to extend its functionality as you wish.
type userApiLimitDao struct {
	internalUserApiLimitDao
}

var (
	// UserApiLimit is globally public accessible object for table user_api_limit operations.
	UserApiLimit = userApiLimitDao{
		internal.NewUserApiLimitDao(),
	}
)

// Fill with you ideas below.
