// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf2/internal/dao/internal"
)

// internalUserMenuDao is internal type for wrapping internal DAO implements.
type internalUserMenuDao = *internal.UserMenuDao

// userMenuDao is the data access object for table user_menu.
// You can define custom methods on it to extend its functionality as you wish.
type userMenuDao struct {
	internalUserMenuDao
}

var (
	// UserMenu is globally public accessible object for table user_menu operations.
	UserMenu = userMenuDao{
		internal.NewUserMenuDao(),
	}
)

// Fill with you ideas below.
