// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf2/internal/dao/internal"
)

// internalWenZhangPingLunDao is internal type for wrapping internal DAO implements.
type internalWenZhangPingLunDao = *internal.WenZhangPingLunDao

// wenZhangPingLunDao is the data access object for table wen_zhang_ping_lun.
// You can define custom methods on it to extend its functionality as you wish.
type wenZhangPingLunDao struct {
	internalWenZhangPingLunDao
}

var (
	// WenZhangPingLun is globally public accessible object for table wen_zhang_ping_lun operations.
	WenZhangPingLun = wenZhangPingLunDao{
		internal.NewWenZhangPingLunDao(),
	}
)

// Fill with you ideas below.
