// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf2/internal/dao/internal"
)

// internalWenZhangDao is internal type for wrapping internal DAO implements.
type internalWenZhangDao = *internal.WenZhangDao

// wenZhangDao is the data access object for table wen_zhang.
// You can define custom methods on it to extend its functionality as you wish.
type wenZhangDao struct {
	internalWenZhangDao
}

var (
	// WenZhang is globally public accessible object for table wen_zhang operations.
	WenZhang = wenZhangDao{
		internal.NewWenZhangDao(),
	}
)

// Fill with you ideas below.
