// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf2/internal/dao/internal"
)

// internalWenzhangfenleiDao is internal type for wrapping internal DAO implements.
type internalWenzhangfenleiDao = *internal.WenzhangfenleiDao

// wenzhangfenleiDao is the data access object for table wenzhangfenlei.
// You can define custom methods on it to extend its functionality as you wish.
type wenzhangfenleiDao struct {
	internalWenzhangfenleiDao
}

var (
	// Wenzhangfenlei is globally public accessible object for table wenzhangfenlei operations.
	Wenzhangfenlei = wenzhangfenleiDao{
		internal.NewWenzhangfenleiDao(),
	}
)

// Fill with you ideas below.
