// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf2/internal/dao/internal"
)

// internalZhaoPinGongSiDao is internal type for wrapping internal DAO implements.
type internalZhaoPinGongSiDao = *internal.ZhaoPinGongSiDao

// zhaoPinGongSiDao is the data access object for table zhao_pin_gong_si.
// You can define custom methods on it to extend its functionality as you wish.
type zhaoPinGongSiDao struct {
	internalZhaoPinGongSiDao
}

var (
	// ZhaoPinGongSi is globally public accessible object for table zhao_pin_gong_si operations.
	ZhaoPinGongSi = zhaoPinGongSiDao{
		internal.NewZhaoPinGongSiDao(),
	}
)

// Fill with you ideas below.
