// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf2/internal/dao/internal"
)

// internalZhaopinFenleiGangweiDao is internal type for wrapping internal DAO implements.
type internalZhaopinFenleiGangweiDao = *internal.ZhaopinFenleiGangweiDao

// zhaopinFenleiGangweiDao is the data access object for table zhaopin_fenlei_gangwei.
// You can define custom methods on it to extend its functionality as you wish.
type zhaopinFenleiGangweiDao struct {
	internalZhaopinFenleiGangweiDao
}

var (
	// ZhaopinFenleiGangwei is globally public accessible object for table zhaopin_fenlei_gangwei operations.
	ZhaopinFenleiGangwei = zhaopinFenleiGangweiDao{
		internal.NewZhaopinFenleiGangweiDao(),
	}
)

// Fill with you ideas below.
